FROM ubuntu:16.04
MAINTAINER Robin Marx <robin.marx@uhasselt.be>

# sudo docker build -t qvis/server:wireshark wireshark/
# sudo docker run --privileged --name qvis_server -d qvis/server:wireshark
# sudo docker exec -it qvis_server bash

#		qt5-default \ 
#		qttools5-dev \ 
#		libqt5svg5-dev \ 
		
# install necessary packages
RUN 						\
	apt-get update 			\
	&& apt-get upgrade -y 	\
	&& apt-get install -y 	\
    	build-essential 	\
		git 				\
		autoconf            \
		libtool             \
		pkg-config          \
		libev-dev           \
		libcap-dev \
		libc-ares-dev \ 
		doxygen \ 
		libgcrypt11-dev \ 
		libglib2.0-dev \ 
		libgnutls28-dev \ 
		krb5-multidev \ 
		flex \ 
		qtmultimedia5-dev \ 
		libssh-dev \ 
		liblz4-dev \ 
		libxml2-dev \ 
		libnghttp2-dev \ 
		libpcap-dev \ 
		libmaxminddb-dev \ 
		libnl-3-dev \ 
		libnl-genl-3-dev \ 
		libnl-route-3-dev \ 
		liblua5.1-0-dev \ 
		liblua50-dev \ 
		liblualib50-dev \ 
		libsbc-dev \ 
		libsmi2-dev \ 
		libsnappy-dev \ 
		libspandsp-dev \ 
		libsystemd-dev \ 
		bison \ 
		asciidoctor \ 
		xsltproc \ 
		cmake \   
		wget \
		python3 \
		gcc \
    && apt-get autoremove 	\
    && apt-get clean		\
	&& rm -rf /var/lib/apt/lists/*
	
RUN git clone --depth 1 https://github.com/BelledonneCommunications/bcg729 /bcg729 \
    && cd /bcg729 \
    && cmake . \
    && make \
    && make install

# https://github.com/wireshark/wireshark/commit/19488f334dfe8d1cf8bc0a80726069e88a2f6335 // draft-22 support with inclusion of packet_length for pcap2qlog in this specific commit 
RUN mkdir /wiresharksrc \
    && cd /wiresharksrc \ 
    && wget https://github.com/wireshark/wireshark/archive/19488f334dfe8d1cf8bc0a80726069e88a2f6335.zip \ 
    && unzip 19488f334dfe8d1cf8bc0a80726069e88a2f6335.zip \
    && rm -f 19488f334dfe8d1cf8bc0a80726069e88a2f6335.zip
 
#RUN apt-get update && apt-get install -y python3 gcc 
#RUN apt-get install -y qttools5-dev qttools5-dev-tools 


RUN mkdir /wireshark \ 
    && cd /wireshark \ 
    && cmake -DBUILD_wireshark=OFF -DBUILD_mergecap=OFF -DBUILD_dftest=OFF -DBUILD_randpkt=OFF -DBUILD_dumpcap=OFF -DBUILD_rawshark=OFF -DENABLE_PCAP=OFF -DENABLE_PLUGINS=OFF /wiresharksrc/wireshark-19488f334dfe8d1cf8bc0a80726069e88a2f6335 \ 
    && make


# cmake -DBUILD_wireshark=OFF -DBUILD_mergecap=OFF -DBUILD_dftest=OFF -DBUILD_randpkt=OFF -DBUILD_dumpcap=OFF -DBUILD_rawshark=OFF -DENABLE_PCAP=OFF -DENABLE_PLUGINS=OFF /wiresharksrc/wireshark-2.9.1rc0-422-g10ef5404 
# RUN mkdir /wireshark && cd /wireshark && cmake /wiresharksrc/wireshark-2.9.1rc0-422-g10ef5404 && make

CMD [ "tail", "-f", "/dev/null" ]
	

